pub mod analysis;
pub mod api;
pub mod components;
pub mod coverage;
pub mod elf;
pub mod emulation;
pub mod engine;
pub mod facts;
pub mod function_ir;
pub mod il;
pub mod lifter;
pub mod object_layout;
pub mod pointer_analysis;
pub mod rc4_search;
pub mod resource_limits;
pub mod xref_graph;
pub mod xref_scan;

pub use api::AeonSession;
